# Generated by Django 3.2.11 on 2025-03-07 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'b_classification',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'b_course',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('log_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'b_error_log',
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('ua', models.CharField(blank=True, max_length=200, null=True)),
                ('log_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'b_login_log',
            },
        ),
        migrations.CreateModel(
            name='OpLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('re_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('re_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('re_url', models.CharField(blank=True, max_length=200, null=True)),
                ('re_method', models.CharField(blank=True, max_length=10, null=True)),
                ('re_content', models.CharField(blank=True, max_length=200, null=True)),
                ('access_time', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'b_op_log',
            },
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='学号')),
                ('contact', models.CharField(max_length=50, verbose_name='联系方式')),
                ('political_status', models.CharField(choices=[('CPC', '共产党员'), ('CYLC', '共青团员'), ('MASS', '群众')], max_length=10, verbose_name='政治面貌')),
                ('social_practice', models.TextField(blank=True, verbose_name='社会实践经历')),
                ('family_members', models.TextField(verbose_name='家庭成员信息')),
                ('family_annual_income', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='家庭年收入')),
                ('income_source', models.CharField(max_length=200, verbose_name='经济来源')),
                ('family_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='家庭负债情况')),
                ('family_health', models.TextField(verbose_name='家庭成员健康状况')),
                ('is_low_income', models.BooleanField(verbose_name='是否享受低保')),
                ('subsidies', models.CharField(blank=True, max_length=200, verbose_name='其他补助')),
                ('emergency_situation', models.TextField(blank=True, verbose_name='突发性经济困难说明')),
                ('academic_performance', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='学业成绩/GPA')),
                ('application_reason', models.TextField(verbose_name='申请理由与用途说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '助学金申请',
                'verbose_name_plural': '助学金申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'b_tag',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '封号')], default='0', max_length=1)),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.FileField(null=True, upload_to='avatar/')),
                ('mobile', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=1, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('push_email', models.CharField(blank=True, max_length=40, null=True)),
                ('push_switch', models.BooleanField(blank=True, default=False, null=True)),
                ('admin_token', models.CharField(blank=True, max_length=32, null=True)),
                ('token', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'b_user',
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('sex', models.CharField(blank=True, max_length=30, null=True)),
                ('age', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('remark', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(choices=[('0', '在住'), ('1', '搬出')], default='0', max_length=1)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classification_thing', to='myapp.classification')),
            ],
            options={
                'db_table': 'b_thing',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.CharField(blank=True, max_length=20, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_score', to='myapp.course')),
                ('thing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thing_score', to='myapp.thing')),
            ],
            options={
                'db_table': 'b_score',
            },
        ),
    ]
