# Generated by Django 3.2.11 on 2025-03-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='academic_performance',
            field=models.CharField(max_length=10, verbose_name='学业成绩/GPA'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='gender',
            field=models.CharField(max_length=5, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='is_low_income',
            field=models.CharField(max_length=5, verbose_name='是否享受低保'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='political_status',
            field=models.CharField(max_length=10, verbose_name='政治面貌'),
        ),
    ]
