# Generated by Django 3.2.11 on 2025-03-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250307_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='family_annual_income',
            field=models.CharField(max_length=15, verbose_name='家庭年收入'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='family_debt',
            field=models.CharField(max_length=15, verbose_name='家庭负债情况'),
        ),
    ]
